kubevirt/kubesecondarydns

manifests/secondarydns.yaml

The auto plugin was checked manually by:
Manually creating a `/zones/db.dns` file via the fedora container.
Exposing the secondary-dns pod.
Running nslookup once the auto plugin refreshed the database.
The RBACs were not tested, but they are a skeleton that can be easily updated 
once we have the informer logic.
Used this as `db.dns`
```
$ORIGIN dns.
$TTL 1750
@       IN      SOA coredns1.dns. coredns0.dns. (
2017042748 ; serial
7200       ; refresh (2 hours)
3600       ; retry (1 hour)
1209600    ; expire (2 weeks)
3600       ; minimum (1 hour)
)
IN NS coredns1.dns.
coredns0                IN  A           1.2.3.4
coredns1                IN  A           1.2.3.4
example                 IN  A           1.2.3.8
```

manifests: Present initial manifest

---

Makefile
cluster/clean.sh
cluster/cli.sh
cluster/cluster.sh
cluster/down.sh
cluster/kubectl.sh
cluster/sync.sh
cluster/up.sh
hack/bump-kubevirtci.sh
hack/functest.sh
hack/install-go.sh
manifests/secondarydns.yaml

Add cluster make targets
Align to the current docker file
allows to deploy the deployment via cluster-sync
The latest kubevirtci which supports DNS is included.
The `test` and `functest` targets are stubs that will be addressed on follow PRs.

makefile: Add basic cluster functions

---

Dockerfile
controllers/virtualmachineinstance_controller.go
main.go

The PR is updating the controller to listen to any VM create/update/delete event without any filtering,
the zoneManager will do the filtering anyway.
It also updates the controller comilation in the docker file to be pinned to linux/amd64.

Remove the filting from the controller and pin the controller compilation to linux/amd64

---

.github/workflows/check.yaml

It seems it is broken
see https://github.com/tisonkun/actions-dco/issues/11 Once we have prow integration, prow plugins will check it.

git actions: Remove dco

---

.github/workflows/check.yaml
Makefile

Add makefile target and github actions of go lint
Remove unneeded go version from github actions.
It is already defined in the makefile, and needed when running locally.

github actions: Add lint

---

manifests/secondarydns.yaml

In order to allow CNAO to consume kube secondary dns 
the manifest should start with a separator,
because CNAO split the manifest according the separator 
in order to parameterize the needed fields.

manifests: Add yaml separator

---

Dockerfile

This will allow us to run shell in the container.
Packages can be installed using microdnf.

Dockerfile: Use ubi minimal base image

---

.github/workflows/image-push.yaml

Image repository should be lower case.
https://github.com/AlonaKaplan/kubesecondarydns/actions/runs/3507917825/jobs/5875956544
```
ERROR: invalid tag "ghcr.io/AlonaKaplan/kubesecondarydns:latest": repository name must be lowercase
Error: buildx failed with: ERROR: invalid tag "ghcr.io/AlonaKaplan/kubesecondarydns:latest": repository name must be lowercase
```

git actions: Fix image push owner

---

Dockerfile

Since podman doesn't support short image url,
use explicit url for go image.
Note: didn't check deploying, only building so far (locally).
The prow e2e is using podman so we will know if there are problems on CI.
Once we have e2e tests I will check end 2 end with podman locally.

podman: Fix building

---

Makefile
cluster/sync.sh
hack/create-nodeport.sh

Present a new make target that allows to create the required node port
(listens to port `31111` as exposed by kubevirtci).
It auto detects the namespace
and can be used either standalone or when deployed by CNAO.
Note: we support only namespaced deployment.

make: Add create node port target

---

cluster/cluster.sh
manifests/secondarydns.yaml

This way we can run commands like `kubectl logs` without specifying
the container with `-c status-monitor`
as we usually need the status-monitor and not the secondary-dns container.
Had to bump to use k8s-1.25 so we can use
`kubectl.kubernetes.io/default-container` and not the deprecated one
`kubectl.kubernetes.io/default-logs-container`.
Note that it works only on 1.25 +

manifest: Add default container

---

.github/workflows/image-push.yaml
Dockerfile
Makefile
README.md

In order to be able to resolve for each image what is the git
commit it was built from using docker inspect.
Can be inspected by using
`docker inspect --format '{{ index .Config.Labels "multi.GIT_URL"}}'`
`docker inspect --format '{{ index .Config.Labels "multi.GIT_SHA"}}'`
Beside that:
2nd commit is a cosmetic to capitalize the first word in a sentence.

Dockerfile: Add git ref labels

---

Makefile
hack/update-manifest.sh
manifests/secondarydns.yaml

Since we push to `ghcr.io/alonakaplan` with github actions,
align all instances in the code to use those registry / repository.
Once we move under kubevirt we will align accordingly.

images: Align registry and repo to be consistent with github actions

---

cluster/up.sh
hack/cna/cna-cr.yaml

Add missing CNAO's CR manifest, in order to allow deploying CNAO and it's CR.
Bump kubevirt so we can create VMs on k8s-1.25 as well.
```release-note
None
```

Add missing CNAO's CR manifest and bump kubevirt

---

.github/PULL_REQUEST_TEMPLATE.md

git actions: Add PR template

---

pkg/zonemgr/zone_file_cache.go
pkg/zonemgr/zone_file_cache_test.go
pkg/zonemgr/zone_file_test.go
pkg/zonemgr/zone_manager.go
pkg/zonemgr/zone_manager_test.go
pkg/zonemgr/zonemgr_suite_test.go

Unit tests added for:
- ZoneManager
- ZoneFileCache
- ZoneFile
Signed-off-by: Diana Teplits <dteplits@redhat.com>
```release-note
None
```

tests, zone manager: Adding unit tests for zone manager component

---

tests/vm_startup_test.go

The PR contains two commits.
The first one is  adding a period to the tested fqdn.
According to the nslokkup man page - 
```
If the lookup request contains at least one period but doesn't end with a trailing period, append the domain names in the domain search list to the request until an answer is received.
To avoid this, a period is added to our fqdn.
```
The second one returns readable `nslookup` error.   
```release-note
NONE
```

[e2e] adding a period to the tested fqdn and improve error readability

---

manifests/secondarydns.yaml
tests/vm_startup_test.go

Use empty strings as default values for the env vars. 
The Zone manager will set the defaults accordingly. 
This allows to deploy the manifest as is.
Since CNAO CR also doesn't have values, it will align the e2e test to
work when running from CNAO (using default values).
```release-note
None
```

manifest: Change default values of env vars

---

cluster/up.sh

It is better to use a stable release.
This way we also don't need to update the major/minor release manually.
```release-note
None
```

kubevirt: Use latest stable release

---

pkg/zonemgr/zone_file_cache.go
pkg/zonemgr/zone_file_cache_test.go

In case custom variables are populated, for example:
```
DOMAIN=secondary.io
NAME_SERVER_IP=1.2.3.4
```
Then the zone file should contain the below two records (KubeSecondaryDNS nameserver details as defined in external domain server):
```
IN NS ns.vm.secondary.io.
ns IN A 1.2.3.4
```
This PR adds `ns` prefix inside the A record as shown above.
`ns` is the default KubeSecondaryDNS nameserver name
The two records eventually will be converted by the DNS engine into this:
```
vm.secondary.io. IN NS ns.vm.secondary.io.
ns.vm.secondary.io. IN A 1.2.3.4
```
- NS record has no prefix, therefore `@` that comes in the line before (SOA record) should catch here. And be replaced by `$ORIGIN` value
- A record has `ns` prefix but no `.` at the end therefore should be completed with  $ORIGIN …

Adding missing nameserver name to custom A record

---

README.md
cluster/cluster.sh
cluster/up.sh
hack/create-nodeport.sh
manifests/secondarydns.yaml

Make secondary-dns deployment PSA ready
Can be tested by -
`kubectl label --dry-run=server --overwrite ns secondary pod-security.kubernetes.io/enforce=restricted`
Without this PR, those kind of warnings are returned - 
```
Warning: existing pods in namespace "secondary" violate the new PodSecurity enforce level "restricted:latest"
Warning: secondary-dns-6fcbb7cf65-8qfnm: allowPrivilegeEscalation != false, unrestricted capabilities, runAsNonRoot != true, seccompProfile
```
https://kubernetes.io/docs/concepts/security/pod-security-admission/
```release-note
Make secondary-dns deployment PSA ready
```

Make secondary-dns deployment PSA ready

---

pkg/controllers/internal/filter/filter_suite_test.go
pkg/controllers/internal/filter/interface_filter.go
pkg/controllers/internal/filter/interface_filter_test.go
pkg/controllers/virtualmachineinstance_controller.go

Reduce the exported methods visibility.
```release-note
NONE
```

controller: Move interface_filter to internal package

---

main.go
pkg/zonemgr/zone_file.go
pkg/zonemgr/zone_file_cache.go
pkg/zonemgr/zone_file_cache_test.go
pkg/zonemgr/zone_file_test.go
pkg/zonemgr/zone_manager.go
pkg/zonemgr/zone_manager_test.go

Flow description:
1. When  status monitor container is loaded, it creates a zone file and initializes it with the header and A records. In this case SOA serial initial value will be 1
2. Each time status monitor updates zone file, it increments SOA serial value
3. Auto plugin inside Corefile is responsible to reload zone file newest data into the DNS when it identifies that SOA serial value was changed
PR adds the below logic:
If status monitor container was reloaded, on its startup it should check whether zone file already exist.
If yes, it should continue the existing SOA serial sequence instead of setting it back to 1. 
The reason for that is the below edge case:
- If zone file already exist and holds SOA serial = 1 (for example) and status monitor container was restarted
- Then even …

Handle status monitor container reload

---

manifests/secondarydns.yaml

Adding resources.requests cpu and memory to status-monitor container.
Remove the resources.limit.memory from the coredns container.
```release-note
NONE
```

Adding cpu and memory requests to status-monitor container and remove limit from the coredns container

---

.github/PULL_REQUEST_TEMPLATE.md

The repository has a github action that generates the changelog of the release with the PR title.
It should be enough.
The PR depends on https://github.com/kubevirt/project-infra/pull/2548

Remove release-note from the PR template

---

manifests/secondarydns.yaml

This PR is part of the Umbrella issue, https://github.com/kubernetes/k8s.io/issues/4780
With the change to defaulting to registry.k8s.io as the image registry and the planned freeze in April, 
downstream projects will likely be impacted, so the image registry needs 
to be updated from k8s.gcr.io to registry.k8s.io.

Updated k8s registry from k8s.gcr.io to registry.k8s.io

---

cluster/sync.sh
cluster/up.sh
hack/psa/kubevirt.yaml

To be able to run VMs on a namespace with restricted PSA policy, KubevirtSeccompProfile feature gate should be enabled and a new configuration needs to be enabled under
.spec.configuration.seccompConfiguration
```
virtualMachineInstanceProfile:
customProfile:
localhostProfile: kubevirt/kubevirt.json
```
Reference: https://github.com/kubevirt/kubevirt/pull/8917

Run kubevirt lane with KUBEVIRT_PSA=true

---

manifests/secondarydns.yaml

Since we moved from k8s.gcr.io to registry.k8s.io
the current version is aliased in those two.
This cause CNAO update test to fail because it expects the new URL 
but the image is detected as the previous one.
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/1552/pull-e2e-cluster-network-addons-operator-lifecycle-k8s/1659558012878065664
Having a new image will solve this, and it should be fine to update the version every now and then.

coreDNS: Bump version

---

pkg/zonemgr/internal/zone-file-cache/zone_file_cache.go
pkg/zonemgr/internal/zone-file-cache/zone_file_cache_test.go

There was a missing `@` at the beginning of the NS record, which caused the line to be invalid, and we didn't get any alerts about it on zone re/load. 
This also broke recourse query for the NS, as the query will be passed to the internal DNS, but the record is missing.
When asking the parent (forcing no recursive query) DNS for the NS, we get a response, 
```
❯ dig NS vm.cnv2.example.com @ns1.eng.example.com +norecurse
; <<>> DiG 9.18.17 <<>> NS vm.cnv2.example.com @ns1.eng.example.com +norecurse
;; global options: +cmd
;; Got answer:
;; ->>HEADER<<- opcode: QUERY, status: NOERROR, id: 32195
;; flags: qr ra; QUERY: 1, ANSWER: 0, AUTHORITY: 1, ADDITIONAL: 2
;; OPT PSEUDOSECTION:
; EDNS: version: 0, flags:; udp: …
```

Fix NS line for the zone file

---

pkg/zonemgr/internal/zone-file-cache/zone_file_cache.go
pkg/zonemgr/internal/zone-file-cache/zone_file_cache_test.go
tests/vm_startup_test.go

make `vm.namespace.<cluster>.` resolve to one of the VM-reported IP addresses. This may make it a bit easier to find the VM even if the user does not recall its interface names.
make `vm.namespace.<cluster>.` resolve to one of the VM-reported IP addresses. This may make it a bit easier to find the VM even if the user does not recall its interface names.
This intends to resolve https://issues.redhat.com/browse/CNV-30087
Finalizing PR https://github.com/kubevirt/kubesecondarydns/pull/60

Add a default A record for each VM

---

tests/vm_generator.go

The cirros image is not supported on s390x, use alpine instead.
Cirros is not built for s390x. Changing it to alpine ensures the e2e test can be run on s390x.

e2e: Change containerdisk from cirros to alpine

---

.github/workflows/image-push.yaml
Dockerfile
hack/install-go.sh

This PR enables building kubesecondarydns for s390x in addition to amd64.
Additionally arm64 is enabled as well, though i can't test it to verify it works.
Additionally it bumps the workflow action versions to their latest to get rid of multiple deprecation warnings.
Finally it fixes a small warning about the case of "AS" in the Dockerfile.
PRs to enable unit-tests and build test for s390x will follow. E2E needs the provider, which for s390x still has some problems to be worked out.

ci: Enable building for s390x and arm64

---

Makefile

When running unit-tests, go tries to compile using CGO, despite not needing it. This can lead to errors on systems not having gcc installed, or named wrongly.
Disable CGO for running unit-tests

Disable CGO when running unit-tests

---

Dockerfile

When cross-building the image for s390x on amd64, podman would use an amd64 image for the base of the final image.
Fix cross-building manually on amd64 with podman.

Dockerfile: Fix wrong base image arch when cross-building with podman

---

manifests/secondarydns.yaml

set the TerminationMessagePolicy field to FallbackToLogsOnError [0]
[0]
https://github.com/redhat-best-practices-for-k8s/certsuite/blob/main/CATALOG.md#observability-termination-policy

Set container's TerminationMessagePolicy to FallbackToLogsOnError

---

manifests/secondarydns.yaml

When using the coredns health and ready plugins they should use different port or unexpected things happends.
The default ports for ready and health plugins are already different 8081 vs 8080
https://github.com/coredns/coredns/tree/master/plugin/ready
https://github.com/coredns/coredns/tree/master/plugin/health

probes: Use different port for coredns ready

---

cluster/sync.sh
hack/install-network-policy.sh
manifests/secondarydns.yaml

Introduce permissive network policies for the project allowing it to coplicy with network restrictions, in form of a global deny-all network policy.
This PR add permissive network-policy allowing ingress to the secondary DNS instance service.
In order to have test coverage, a deny-all network-policy is installed as part of the cluster-sync flow.
Having it installed as part of the cluster-sync flow ensure coverage for dev and tests envs, locally and on CI.
In addition to the deny-all NP, a permissive policy allowing access to cluster API and DNS is installed, as it is fundamental requirement for any k8s controller:
- Allow egress to cluster DNS
Enable interaction with cluster DNS, w/o this policy the
KSD manager …

Add Network policies
